### ISSUE TITLE
Cannot run exe

### ISSUE THREAD

**Issue by ceoy** [Kuraikari/Modern-Times#13]
When trying to run the game.exe, i get following error:

_There should be 'game_Data'
folder next to the executable_

Help.

**Comment by Kuraikari** [comment]
Hello Tim,

Thank you for letting me know, that I am that stupid. I'll upload the needed files ASAP.

Have a nice day.

Best regards 

Wermelinger Zian

**Comment by ceoy** [comment]
worked after moving the exe into the data folder, thanks:)
is there anything special i do or a place i should visit ingame?

**Comment by Kuraikari** [comment]
Well, try the south direction, to get to the school. :) 

Freundliche Grüsse

Wermelinger Zian
